services: 
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "my_database"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    
  api:
    build: ./api
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      - /app/node_modules
  cache:
    image: redis:latest
    ports:
      - "6379:6379"
  testcontainer:
    image: alpine:latest
    command: sleep infinity

volumes:
  db-data: