services: 
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "my-secret-pw"
      POSTGRES_DB: "my_database"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    
  api:
    build: ./api
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://postgres:my-secret-pw@db:5432/my_database
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  db-data: